///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SetupButtons
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SetupButtonsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("4418ccdd-43ae-4ffd-a553-200e1e7ccedf")]
    public partial class SetupButtonsRepository : RepoGenBaseFolder
    {
        static SetupButtonsRepository instance = new SetupButtonsRepository();
        SetupButtonsRepositoryFolders.SnapXUntitledAppFolder _snapxuntitled;

        /// <summary>
        /// Gets the singleton class instance representing the SetupButtonsRepository element repository.
        /// </summary>
        [RepositoryFolder("4418ccdd-43ae-4ffd-a553-200e1e7ccedf")]
        public static SetupButtonsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SetupButtonsRepository() 
            : base("SetupButtonsRepository", "/", null, 0, false, "4418ccdd-43ae-4ffd-a553-200e1e7ccedf", ".\\RepositoryImages\\SetupButtonsRepository4418ccdd.rximgres")
        {
            _snapxuntitled = new SetupButtonsRepositoryFolders.SnapXUntitledAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("4418ccdd-43ae-4ffd-a553-200e1e7ccedf")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SnapXUntitled folder.
        /// </summary>
        [RepositoryFolder("b254928d-18c4-490a-af3e-4863bcb3b652")]
        public virtual SetupButtonsRepositoryFolders.SnapXUntitledAppFolder SnapXUntitled
        {
            get { return _snapxuntitled; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class SetupButtonsRepositoryFolders
    {
        /// <summary>
        /// The SnapXUntitledAppFolder folder.
        /// </summary>
        [RepositoryFolder("b254928d-18c4-490a-af3e-4863bcb3b652")]
        public partial class SnapXUntitledAppFolder : RepoGenBaseFolder
        {
            SetupButtonsRepositoryFolders.SNAPXFolder _snapx;
            RepoItemInfo _snapxuntitledInfo;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new SnapXUntitled  folder.
            /// </summary>
            public SnapXUntitledAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SnapXUntitled", "/form[@title='Snap-X - [Untitled]']", parentFolder, 30000, null, true, "b254928d-18c4-490a-af3e-4863bcb3b652", "")
            {
                _snapx = new SetupButtonsRepositoryFolders.SNAPXFolder(this);
                _snapxuntitledInfo = new RepoItemInfo(this, "SnapXUntitled", "titlebar[@accessiblerole='TitleBar']", 30000, null, "a490858b-7729-4f3a-8139-bc9c34a7f400");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "container[@controlid='59648']/form[@controlid='65281']//button[@text='&OK']", 30000, null, "439fa98f-21e9-472f-90b9-b22e9426c1c2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b254928d-18c4-490a-af3e-4863bcb3b652")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b254928d-18c4-490a-af3e-4863bcb3b652")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SnapXUntitled item.
            /// </summary>
            [RepositoryItem("a490858b-7729-4f3a-8139-bc9c34a7f400")]
            public virtual Ranorex.TitleBar SnapXUntitled
            {
                get
                {
                    return _snapxuntitledInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The SnapXUntitled item info.
            /// </summary>
            [RepositoryItemInfo("a490858b-7729-4f3a-8139-bc9c34a7f400")]
            public virtual RepoItemInfo SnapXUntitledInfo
            {
                get
                {
                    return _snapxuntitledInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("439fa98f-21e9-472f-90b9-b22e9426c1c2")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("439fa98f-21e9-472f-90b9-b22e9426c1c2")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The SNAPX folder.
            /// </summary>
            [RepositoryFolder("12f8a52b-969f-47aa-9e76-39b465efd270")]
            public virtual SetupButtonsRepositoryFolders.SNAPXFolder SNAPX
            {
                get { return _snapx; }
            }
        }

        /// <summary>
        /// The SNAPXFolder folder.
        /// </summary>
        [RepositoryFolder("12f8a52b-969f-47aa-9e76-39b465efd270")]
        public partial class SNAPXFolder : RepoGenBaseFolder
        {
            RepoItemInfo _zeroxaxisInfo;
            RepoItemInfo _zeroyaxisInfo;
            RepoItemInfo _modifiersInfo;
            RepoItemInfo _zeroaxisInfo;
            RepoItemInfo _setaxisInfo;
            RepoItemInfo _atactuallocationInfo;
            RepoItemInfo _atnominallocationInfo;
            RepoItemInfo _featurestextInfo;
            RepoItemInfo _boxforvalueInfo;
            RepoItemInfo _setxaxistotextInfo;
            RepoItemInfo _setyaxistotextInfo;
            RepoItemInfo _entirewindowInfo;
            RepoItemInfo _atfeatureorientationInfo;
            RepoItemInfo _alignaxisInfo;
            RepoItemInfo _radiobuttonxInfo;
            RepoItemInfo _radiobuttonyInfo;
            RepoItemInfo _setalignmentInfo;
            RepoItemInfo _alignaxistoangletextInfo;
            RepoItemInfo _setbasicalignmentInfo;
            RepoItemInfo _xbasicInfo;
            RepoItemInfo _ybasicInfo;
            RepoItemInfo _setbasicvaluetextInfo;
            RepoItemInfo _featuresInfo;
            RepoItemInfo _datumInfo;
            RepoItemInfo _recalltextInfo;
            RepoItemInfo _inputfromfileInfo;
            RepoItemInfo _inputfromfiletextInfo;
            RepoItemInfo _keepfileInfo;
            RepoItemInfo _filepathnametextInfo;
            RepoItemInfo _methodInfo;
            RepoItemInfo _centroidInfo;
            RepoItemInfo _edgemaskInfo;
            RepoItemInfo _multipleInfo;
            RepoItemInfo _multiple1Info;
            RepoItemInfo _thresholdInfo;
            RepoItemInfo _filterInfo;
            RepoItemInfo _nonetextInfo;
            RepoItemInfo _maxtextInfo;
            RepoItemInfo _fillInfo;
            RepoItemInfo _touchboundaryInfo;

            /// <summary>
            /// Creates a new SNAPX  folder.
            /// </summary>
            public SNAPXFolder(RepoGenBaseFolder parentFolder) :
                    base("SNAPX", "container[@controlid='59648']/form[@controlid='65281']//container[@controlid='59648']/container[@class='#32770']", parentFolder, 30000, null, false, "12f8a52b-969f-47aa-9e76-39b465efd270", "")
            {
                _zeroxaxisInfo = new RepoItemInfo(this, "ZeroXAxis", "?/?/checkbox[@text='Zero X Axis']", 30000, null, "a8d7fa7e-ebf3-4e18-92bc-cb842d1861e4");
                _zeroyaxisInfo = new RepoItemInfo(this, "ZeroYAxis", "?/?/checkbox[@text='Zero Y Axis']", 30000, null, "7d64390c-ab8a-45bf-808d-8f6c237c968d");
                _modifiersInfo = new RepoItemInfo(this, "Modifiers", "?/?/container[@controlid='1471']/container[@accessiblename='Modifiers']", 30000, null, "f099cf4b-2977-493a-b40d-c953160396a3");
                _zeroaxisInfo = new RepoItemInfo(this, "ZeroAxis", "?/?/container[@controlid='1474']/container[@accessiblename='Zero Axis']", 30000, null, "6fd446e6-1bc1-4bf4-96d9-52fc6cd6d98d");
                _setaxisInfo = new RepoItemInfo(this, "SetAxis", "?/?/container[@controlid='1475']/container[@accessiblename='Set Axis']", 30000, null, "a56db0c8-3075-430f-b229-47b45a7c653d");
                _atactuallocationInfo = new RepoItemInfo(this, "AtActualLocation", "?/?/radiobutton[@text='At Actual Location']", 30000, null, "312d60af-f11a-4398-9a0a-28b39b974142");
                _atnominallocationInfo = new RepoItemInfo(this, "AtNominalLocation", "?/?/radiobutton[@text='At Nominal Location']", 30000, null, "821caabf-6bf4-4498-9120-531f7e3fd28f");
                _featurestextInfo = new RepoItemInfo(this, "FeaturesText", "?/?/text[@controlid='1217']", 30000, null, "146b5325-b760-4c16-a7dc-2600a6d517bc");
                _boxforvalueInfo = new RepoItemInfo(this, "BoxForValue", "?/?/text[@controlid='1227']", 30000, null, "eda461a2-dca3-4b60-91de-8627db70a455");
                _setxaxistotextInfo = new RepoItemInfo(this, "SetXAxisToText", "?/?/text[@controlid='1476']", 30000, null, "ce791093-5b85-4b21-b9f6-2e1a45d39883");
                _setyaxistotextInfo = new RepoItemInfo(this, "SetYAxisToText", "?/?/text[@controlid='1477']", 30000, null, "85a9840e-e002-4020-8729-13f6f19246a3");
                _entirewindowInfo = new RepoItemInfo(this, "EntireWindow", "container[@class='#32770']", 30000, null, "c9146bdd-2eec-40ef-9425-9ad0d6e63cb6");
                _atfeatureorientationInfo = new RepoItemInfo(this, "AtFeatureOrientation", "?/?/radiobutton[@text='At Feature Orientation']", 30000, null, "739add65-b0a5-475d-b0d4-2993d890dc32");
                _alignaxisInfo = new RepoItemInfo(this, "AlignAxis", "?/?/container[@controlid='1468']/container[@accessiblename='Align Axis']", 30000, null, "237fb62c-6456-4c80-a439-527a4def6581");
                _radiobuttonxInfo = new RepoItemInfo(this, "RadioButtonX", "?/?/radiobutton[@text='X']", 30000, null, "2b5abb49-2f0f-4106-9c10-d21f6530ad04");
                _radiobuttonyInfo = new RepoItemInfo(this, "RadioButtonY", "?/?/radiobutton[@text='Y']", 30000, null, "a7fca8a7-e49d-4365-9464-a11ec05c3c0f");
                _setalignmentInfo = new RepoItemInfo(this, "SetAlignment", "?/?/container[@controlid='1469']/container[@accessiblename='Set Alignment']", 30000, null, "71814626-f769-4897-9929-372a40eeab55");
                _alignaxistoangletextInfo = new RepoItemInfo(this, "AlignAxisToAngleText", "?/?/text[@controlid='1472']", 30000, null, "e35b83e1-6e2f-46d7-bce2-c57362622b6a");
                _setbasicalignmentInfo = new RepoItemInfo(this, "SetBasicAlignment", "?/?/container[@controlid='1470']/container[@accessiblename='Set Basic Alignment']", 30000, null, "f24306d4-b7f8-4a92-865a-2a2217a9cc40");
                _xbasicInfo = new RepoItemInfo(this, "XBasic", "?/?/radiobutton[@text='X Basic']", 30000, null, "c2635525-51b1-465f-aeba-6b83712b97c2");
                _ybasicInfo = new RepoItemInfo(this, "YBasic", "?/?/radiobutton[@text='Y Basic']", 30000, null, "17ddc925-b7f1-4da3-a125-24c4e81cc52d");
                _setbasicvaluetextInfo = new RepoItemInfo(this, "SetBasicValueText", "?/?/text[@controlid='1473']", 30000, null, "2a11ddd2-e12d-408c-a1d4-6312006d6523");
                _featuresInfo = new RepoItemInfo(this, "Features", "?/?/button[@text='Features']", 30000, null, "c09044ed-e750-458d-9418-ce1c047e3f46");
                _datumInfo = new RepoItemInfo(this, "Datum", "?/?/container[@controlid='2602']/container[@accessiblename='Datum']", 30000, null, "233df5ce-d572-4277-8987-03623c824c39");
                _recalltextInfo = new RepoItemInfo(this, "RecallText", "?/?/text[@controlid='2601']", 30000, null, "8d92d3bd-f507-4f86-ad29-15928e294e3b");
                _inputfromfileInfo = new RepoItemInfo(this, "InputFromFile", "?/?/container[@controlid='3145']/container[@accessiblename='Input From File']", 30000, null, "c6bf584c-04a2-4525-a4ed-7e12f96dd2cd");
                _inputfromfiletextInfo = new RepoItemInfo(this, "InputFromFileText", "?/?/checkbox[@text='Input From File']", 30000, null, "59544735-787f-4c04-9252-e4eaf8b8a2e9");
                _keepfileInfo = new RepoItemInfo(this, "KeepFile", "?/?/checkbox[@text='Keep File']", 30000, null, "ceb2a227-3cdf-4fee-a613-0ab275be7bc5");
                _filepathnametextInfo = new RepoItemInfo(this, "FilePathnameText", "?/?/text[@controlid='3141']", 30000, null, "69384270-e1ba-45f8-8f7c-1cb4b0850420");
                _methodInfo = new RepoItemInfo(this, "Method", "?/?/container[@controlid='3035']/container[@accessiblename='Method']", 30000, null, "013c4baa-aea9-4669-bca4-bf2707b36770");
                _centroidInfo = new RepoItemInfo(this, "Centroid", "?/?/radiobutton[@text='Centroid']", 30000, null, "1136ab0e-9534-4de7-95e2-7bb9ef220656");
                _edgemaskInfo = new RepoItemInfo(this, "EdgeMask", "?/?/radiobutton[@text='Edge Mask']", 30000, null, "9ffe884a-c1a0-4dd4-9b49-fcce233673d9");
                _multipleInfo = new RepoItemInfo(this, "Multiple", "?/?/container[@class='#32770']/container[@caption='Multiple']/container[@accessiblename='Multiple']", 30000, null, "e192728e-1716-4b3c-a599-0da081d5d187");
                _multiple1Info = new RepoItemInfo(this, "Multiple1", "?/?/container[@class='#32770']/checkbox[@text='Multiple']", 30000, null, "7af06cb0-2e9a-4965-b000-843e1d925ef7");
                _thresholdInfo = new RepoItemInfo(this, "Threshold", "?/?/container[@controlid='2100' and @class='Button' and @instance='1']/container[@accessiblename='Threshold']", 30000, null, "86dae624-110f-49b9-ad50-6dc848f9acd5");
                _filterInfo = new RepoItemInfo(this, "Filter", "?/?/container[@class='#32770']/container[@caption='Filter']/container[@accessiblename='Filter']", 30000, null, "fcc04890-5368-4344-8624-9db905c9d091");
                _nonetextInfo = new RepoItemInfo(this, "NoneText", "?/?/container[@class='#32770']/text[@controlid='2106']", 30000, null, "ed2e6d66-1e77-45ad-bb32-d90d07a73a83");
                _maxtextInfo = new RepoItemInfo(this, "MaxText", "?/?/container[@class='#32770']/text[@controlid='2112']", 30000, null, "024dea1c-6184-4359-9836-f51dcdd8f495");
                _fillInfo = new RepoItemInfo(this, "Fill", "?/?/container[@class='#32770']/checkbox[@text='Fill']", 30000, null, "4b81c6c1-619d-4bfb-b623-1a3bd83b3cee");
                _touchboundaryInfo = new RepoItemInfo(this, "TouchBoundary", "?/?/container[@class='#32770']/checkbox[@text='Touch Boundary']", 30000, null, "5fa6715f-d154-46a1-ace7-467c984e2bc3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("12f8a52b-969f-47aa-9e76-39b465efd270")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("12f8a52b-969f-47aa-9e76-39b465efd270")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ZeroXAxis item.
            /// </summary>
            [RepositoryItem("a8d7fa7e-ebf3-4e18-92bc-cb842d1861e4")]
            public virtual Ranorex.CheckBox ZeroXAxis
            {
                get
                {
                    return _zeroxaxisInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ZeroXAxis item info.
            /// </summary>
            [RepositoryItemInfo("a8d7fa7e-ebf3-4e18-92bc-cb842d1861e4")]
            public virtual RepoItemInfo ZeroXAxisInfo
            {
                get
                {
                    return _zeroxaxisInfo;
                }
            }

            /// <summary>
            /// The ZeroYAxis item.
            /// </summary>
            [RepositoryItem("7d64390c-ab8a-45bf-808d-8f6c237c968d")]
            public virtual Ranorex.CheckBox ZeroYAxis
            {
                get
                {
                    return _zeroyaxisInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ZeroYAxis item info.
            /// </summary>
            [RepositoryItemInfo("7d64390c-ab8a-45bf-808d-8f6c237c968d")]
            public virtual RepoItemInfo ZeroYAxisInfo
            {
                get
                {
                    return _zeroyaxisInfo;
                }
            }

            /// <summary>
            /// The Modifiers item.
            /// </summary>
            [RepositoryItem("f099cf4b-2977-493a-b40d-c953160396a3")]
            public virtual Ranorex.Container Modifiers
            {
                get
                {
                    return _modifiersInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Modifiers item info.
            /// </summary>
            [RepositoryItemInfo("f099cf4b-2977-493a-b40d-c953160396a3")]
            public virtual RepoItemInfo ModifiersInfo
            {
                get
                {
                    return _modifiersInfo;
                }
            }

            /// <summary>
            /// The ZeroAxis item.
            /// </summary>
            [RepositoryItem("6fd446e6-1bc1-4bf4-96d9-52fc6cd6d98d")]
            public virtual Ranorex.Container ZeroAxis
            {
                get
                {
                    return _zeroaxisInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ZeroAxis item info.
            /// </summary>
            [RepositoryItemInfo("6fd446e6-1bc1-4bf4-96d9-52fc6cd6d98d")]
            public virtual RepoItemInfo ZeroAxisInfo
            {
                get
                {
                    return _zeroaxisInfo;
                }
            }

            /// <summary>
            /// The SetAxis item.
            /// </summary>
            [RepositoryItem("a56db0c8-3075-430f-b229-47b45a7c653d")]
            public virtual Ranorex.Container SetAxis
            {
                get
                {
                    return _setaxisInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SetAxis item info.
            /// </summary>
            [RepositoryItemInfo("a56db0c8-3075-430f-b229-47b45a7c653d")]
            public virtual RepoItemInfo SetAxisInfo
            {
                get
                {
                    return _setaxisInfo;
                }
            }

            /// <summary>
            /// The AtActualLocation item.
            /// </summary>
            [RepositoryItem("312d60af-f11a-4398-9a0a-28b39b974142")]
            public virtual Ranorex.RadioButton AtActualLocation
            {
                get
                {
                    return _atactuallocationInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The AtActualLocation item info.
            /// </summary>
            [RepositoryItemInfo("312d60af-f11a-4398-9a0a-28b39b974142")]
            public virtual RepoItemInfo AtActualLocationInfo
            {
                get
                {
                    return _atactuallocationInfo;
                }
            }

            /// <summary>
            /// The AtNominalLocation item.
            /// </summary>
            [RepositoryItem("821caabf-6bf4-4498-9120-531f7e3fd28f")]
            public virtual Ranorex.RadioButton AtNominalLocation
            {
                get
                {
                    return _atnominallocationInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The AtNominalLocation item info.
            /// </summary>
            [RepositoryItemInfo("821caabf-6bf4-4498-9120-531f7e3fd28f")]
            public virtual RepoItemInfo AtNominalLocationInfo
            {
                get
                {
                    return _atnominallocationInfo;
                }
            }

            /// <summary>
            /// The FeaturesText item.
            /// </summary>
            [RepositoryItem("146b5325-b760-4c16-a7dc-2600a6d517bc")]
            public virtual Ranorex.Text FeaturesText
            {
                get
                {
                    return _featurestextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FeaturesText item info.
            /// </summary>
            [RepositoryItemInfo("146b5325-b760-4c16-a7dc-2600a6d517bc")]
            public virtual RepoItemInfo FeaturesTextInfo
            {
                get
                {
                    return _featurestextInfo;
                }
            }

            /// <summary>
            /// The BoxForValue item.
            /// </summary>
            [RepositoryItem("eda461a2-dca3-4b60-91de-8627db70a455")]
            public virtual Ranorex.Text BoxForValue
            {
                get
                {
                    return _boxforvalueInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BoxForValue item info.
            /// </summary>
            [RepositoryItemInfo("eda461a2-dca3-4b60-91de-8627db70a455")]
            public virtual RepoItemInfo BoxForValueInfo
            {
                get
                {
                    return _boxforvalueInfo;
                }
            }

            /// <summary>
            /// The SetXAxisToText item.
            /// </summary>
            [RepositoryItem("ce791093-5b85-4b21-b9f6-2e1a45d39883")]
            public virtual Ranorex.Text SetXAxisToText
            {
                get
                {
                    return _setxaxistotextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SetXAxisToText item info.
            /// </summary>
            [RepositoryItemInfo("ce791093-5b85-4b21-b9f6-2e1a45d39883")]
            public virtual RepoItemInfo SetXAxisToTextInfo
            {
                get
                {
                    return _setxaxistotextInfo;
                }
            }

            /// <summary>
            /// The SetYAxisToText item.
            /// </summary>
            [RepositoryItem("85a9840e-e002-4020-8729-13f6f19246a3")]
            public virtual Ranorex.Text SetYAxisToText
            {
                get
                {
                    return _setyaxistotextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SetYAxisToText item info.
            /// </summary>
            [RepositoryItemInfo("85a9840e-e002-4020-8729-13f6f19246a3")]
            public virtual RepoItemInfo SetYAxisToTextInfo
            {
                get
                {
                    return _setyaxistotextInfo;
                }
            }

            /// <summary>
            /// The EntireWindow item.
            /// </summary>
            [RepositoryItem("c9146bdd-2eec-40ef-9425-9ad0d6e63cb6")]
            public virtual Ranorex.Container EntireWindow
            {
                get
                {
                    return _entirewindowInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The EntireWindow item info.
            /// </summary>
            [RepositoryItemInfo("c9146bdd-2eec-40ef-9425-9ad0d6e63cb6")]
            public virtual RepoItemInfo EntireWindowInfo
            {
                get
                {
                    return _entirewindowInfo;
                }
            }

            /// <summary>
            /// The AtFeatureOrientation item.
            /// </summary>
            [RepositoryItem("739add65-b0a5-475d-b0d4-2993d890dc32")]
            public virtual Ranorex.RadioButton AtFeatureOrientation
            {
                get
                {
                    return _atfeatureorientationInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The AtFeatureOrientation item info.
            /// </summary>
            [RepositoryItemInfo("739add65-b0a5-475d-b0d4-2993d890dc32")]
            public virtual RepoItemInfo AtFeatureOrientationInfo
            {
                get
                {
                    return _atfeatureorientationInfo;
                }
            }

            /// <summary>
            /// The AlignAxis item.
            /// </summary>
            [RepositoryItem("237fb62c-6456-4c80-a439-527a4def6581")]
            public virtual Ranorex.Container AlignAxis
            {
                get
                {
                    return _alignaxisInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The AlignAxis item info.
            /// </summary>
            [RepositoryItemInfo("237fb62c-6456-4c80-a439-527a4def6581")]
            public virtual RepoItemInfo AlignAxisInfo
            {
                get
                {
                    return _alignaxisInfo;
                }
            }

            /// <summary>
            /// The RadioButtonX item.
            /// </summary>
            [RepositoryItem("2b5abb49-2f0f-4106-9c10-d21f6530ad04")]
            public virtual Ranorex.RadioButton RadioButtonX
            {
                get
                {
                    return _radiobuttonxInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RadioButtonX item info.
            /// </summary>
            [RepositoryItemInfo("2b5abb49-2f0f-4106-9c10-d21f6530ad04")]
            public virtual RepoItemInfo RadioButtonXInfo
            {
                get
                {
                    return _radiobuttonxInfo;
                }
            }

            /// <summary>
            /// The RadioButtonY item.
            /// </summary>
            [RepositoryItem("a7fca8a7-e49d-4365-9464-a11ec05c3c0f")]
            public virtual Ranorex.RadioButton RadioButtonY
            {
                get
                {
                    return _radiobuttonyInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RadioButtonY item info.
            /// </summary>
            [RepositoryItemInfo("a7fca8a7-e49d-4365-9464-a11ec05c3c0f")]
            public virtual RepoItemInfo RadioButtonYInfo
            {
                get
                {
                    return _radiobuttonyInfo;
                }
            }

            /// <summary>
            /// The SetAlignment item.
            /// </summary>
            [RepositoryItem("71814626-f769-4897-9929-372a40eeab55")]
            public virtual Ranorex.Container SetAlignment
            {
                get
                {
                    return _setalignmentInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SetAlignment item info.
            /// </summary>
            [RepositoryItemInfo("71814626-f769-4897-9929-372a40eeab55")]
            public virtual RepoItemInfo SetAlignmentInfo
            {
                get
                {
                    return _setalignmentInfo;
                }
            }

            /// <summary>
            /// The AlignAxisToAngleText item.
            /// </summary>
            [RepositoryItem("e35b83e1-6e2f-46d7-bce2-c57362622b6a")]
            public virtual Ranorex.Text AlignAxisToAngleText
            {
                get
                {
                    return _alignaxistoangletextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AlignAxisToAngleText item info.
            /// </summary>
            [RepositoryItemInfo("e35b83e1-6e2f-46d7-bce2-c57362622b6a")]
            public virtual RepoItemInfo AlignAxisToAngleTextInfo
            {
                get
                {
                    return _alignaxistoangletextInfo;
                }
            }

            /// <summary>
            /// The SetBasicAlignment item.
            /// </summary>
            [RepositoryItem("f24306d4-b7f8-4a92-865a-2a2217a9cc40")]
            public virtual Ranorex.Container SetBasicAlignment
            {
                get
                {
                    return _setbasicalignmentInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The SetBasicAlignment item info.
            /// </summary>
            [RepositoryItemInfo("f24306d4-b7f8-4a92-865a-2a2217a9cc40")]
            public virtual RepoItemInfo SetBasicAlignmentInfo
            {
                get
                {
                    return _setbasicalignmentInfo;
                }
            }

            /// <summary>
            /// The XBasic item.
            /// </summary>
            [RepositoryItem("c2635525-51b1-465f-aeba-6b83712b97c2")]
            public virtual Ranorex.RadioButton XBasic
            {
                get
                {
                    return _xbasicInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The XBasic item info.
            /// </summary>
            [RepositoryItemInfo("c2635525-51b1-465f-aeba-6b83712b97c2")]
            public virtual RepoItemInfo XBasicInfo
            {
                get
                {
                    return _xbasicInfo;
                }
            }

            /// <summary>
            /// The YBasic item.
            /// </summary>
            [RepositoryItem("17ddc925-b7f1-4da3-a125-24c4e81cc52d")]
            public virtual Ranorex.RadioButton YBasic
            {
                get
                {
                    return _ybasicInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The YBasic item info.
            /// </summary>
            [RepositoryItemInfo("17ddc925-b7f1-4da3-a125-24c4e81cc52d")]
            public virtual RepoItemInfo YBasicInfo
            {
                get
                {
                    return _ybasicInfo;
                }
            }

            /// <summary>
            /// The SetBasicValueText item.
            /// </summary>
            [RepositoryItem("2a11ddd2-e12d-408c-a1d4-6312006d6523")]
            public virtual Ranorex.Text SetBasicValueText
            {
                get
                {
                    return _setbasicvaluetextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SetBasicValueText item info.
            /// </summary>
            [RepositoryItemInfo("2a11ddd2-e12d-408c-a1d4-6312006d6523")]
            public virtual RepoItemInfo SetBasicValueTextInfo
            {
                get
                {
                    return _setbasicvaluetextInfo;
                }
            }

            /// <summary>
            /// The Features item.
            /// </summary>
            [RepositoryItem("c09044ed-e750-458d-9418-ce1c047e3f46")]
            public virtual Ranorex.Button Features
            {
                get
                {
                    return _featuresInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Features item info.
            /// </summary>
            [RepositoryItemInfo("c09044ed-e750-458d-9418-ce1c047e3f46")]
            public virtual RepoItemInfo FeaturesInfo
            {
                get
                {
                    return _featuresInfo;
                }
            }

            /// <summary>
            /// The Datum item.
            /// </summary>
            [RepositoryItem("233df5ce-d572-4277-8987-03623c824c39")]
            public virtual Ranorex.Container Datum
            {
                get
                {
                    return _datumInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Datum item info.
            /// </summary>
            [RepositoryItemInfo("233df5ce-d572-4277-8987-03623c824c39")]
            public virtual RepoItemInfo DatumInfo
            {
                get
                {
                    return _datumInfo;
                }
            }

            /// <summary>
            /// The RecallText item.
            /// </summary>
            [RepositoryItem("8d92d3bd-f507-4f86-ad29-15928e294e3b")]
            public virtual Ranorex.Text RecallText
            {
                get
                {
                    return _recalltextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RecallText item info.
            /// </summary>
            [RepositoryItemInfo("8d92d3bd-f507-4f86-ad29-15928e294e3b")]
            public virtual RepoItemInfo RecallTextInfo
            {
                get
                {
                    return _recalltextInfo;
                }
            }

            /// <summary>
            /// The InputFromFile item.
            /// </summary>
            [RepositoryItem("c6bf584c-04a2-4525-a4ed-7e12f96dd2cd")]
            public virtual Ranorex.Container InputFromFile
            {
                get
                {
                    return _inputfromfileInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The InputFromFile item info.
            /// </summary>
            [RepositoryItemInfo("c6bf584c-04a2-4525-a4ed-7e12f96dd2cd")]
            public virtual RepoItemInfo InputFromFileInfo
            {
                get
                {
                    return _inputfromfileInfo;
                }
            }

            /// <summary>
            /// The InputFromFileText item.
            /// </summary>
            [RepositoryItem("59544735-787f-4c04-9252-e4eaf8b8a2e9")]
            public virtual Ranorex.CheckBox InputFromFileText
            {
                get
                {
                    return _inputfromfiletextInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The InputFromFileText item info.
            /// </summary>
            [RepositoryItemInfo("59544735-787f-4c04-9252-e4eaf8b8a2e9")]
            public virtual RepoItemInfo InputFromFileTextInfo
            {
                get
                {
                    return _inputfromfiletextInfo;
                }
            }

            /// <summary>
            /// The KeepFile item.
            /// </summary>
            [RepositoryItem("ceb2a227-3cdf-4fee-a613-0ab275be7bc5")]
            public virtual Ranorex.CheckBox KeepFile
            {
                get
                {
                    return _keepfileInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The KeepFile item info.
            /// </summary>
            [RepositoryItemInfo("ceb2a227-3cdf-4fee-a613-0ab275be7bc5")]
            public virtual RepoItemInfo KeepFileInfo
            {
                get
                {
                    return _keepfileInfo;
                }
            }

            /// <summary>
            /// The FilePathnameText item.
            /// </summary>
            [RepositoryItem("69384270-e1ba-45f8-8f7c-1cb4b0850420")]
            public virtual Ranorex.Text FilePathnameText
            {
                get
                {
                    return _filepathnametextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FilePathnameText item info.
            /// </summary>
            [RepositoryItemInfo("69384270-e1ba-45f8-8f7c-1cb4b0850420")]
            public virtual RepoItemInfo FilePathnameTextInfo
            {
                get
                {
                    return _filepathnametextInfo;
                }
            }

            /// <summary>
            /// The Method item.
            /// </summary>
            [RepositoryItem("013c4baa-aea9-4669-bca4-bf2707b36770")]
            public virtual Ranorex.Container Method
            {
                get
                {
                    return _methodInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Method item info.
            /// </summary>
            [RepositoryItemInfo("013c4baa-aea9-4669-bca4-bf2707b36770")]
            public virtual RepoItemInfo MethodInfo
            {
                get
                {
                    return _methodInfo;
                }
            }

            /// <summary>
            /// The Centroid item.
            /// </summary>
            [RepositoryItem("1136ab0e-9534-4de7-95e2-7bb9ef220656")]
            public virtual Ranorex.RadioButton Centroid
            {
                get
                {
                    return _centroidInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The Centroid item info.
            /// </summary>
            [RepositoryItemInfo("1136ab0e-9534-4de7-95e2-7bb9ef220656")]
            public virtual RepoItemInfo CentroidInfo
            {
                get
                {
                    return _centroidInfo;
                }
            }

            /// <summary>
            /// The EdgeMask item.
            /// </summary>
            [RepositoryItem("9ffe884a-c1a0-4dd4-9b49-fcce233673d9")]
            public virtual Ranorex.RadioButton EdgeMask
            {
                get
                {
                    return _edgemaskInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The EdgeMask item info.
            /// </summary>
            [RepositoryItemInfo("9ffe884a-c1a0-4dd4-9b49-fcce233673d9")]
            public virtual RepoItemInfo EdgeMaskInfo
            {
                get
                {
                    return _edgemaskInfo;
                }
            }

            /// <summary>
            /// The Multiple item.
            /// </summary>
            [RepositoryItem("e192728e-1716-4b3c-a599-0da081d5d187")]
            public virtual Ranorex.Container Multiple
            {
                get
                {
                    return _multipleInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Multiple item info.
            /// </summary>
            [RepositoryItemInfo("e192728e-1716-4b3c-a599-0da081d5d187")]
            public virtual RepoItemInfo MultipleInfo
            {
                get
                {
                    return _multipleInfo;
                }
            }

            /// <summary>
            /// The Multiple1 item.
            /// </summary>
            [RepositoryItem("7af06cb0-2e9a-4965-b000-843e1d925ef7")]
            public virtual Ranorex.CheckBox Multiple1
            {
                get
                {
                    return _multiple1Info.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The Multiple1 item info.
            /// </summary>
            [RepositoryItemInfo("7af06cb0-2e9a-4965-b000-843e1d925ef7")]
            public virtual RepoItemInfo Multiple1Info
            {
                get
                {
                    return _multiple1Info;
                }
            }

            /// <summary>
            /// The Threshold item.
            /// </summary>
            [RepositoryItem("86dae624-110f-49b9-ad50-6dc848f9acd5")]
            public virtual Ranorex.Container Threshold
            {
                get
                {
                    return _thresholdInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Threshold item info.
            /// </summary>
            [RepositoryItemInfo("86dae624-110f-49b9-ad50-6dc848f9acd5")]
            public virtual RepoItemInfo ThresholdInfo
            {
                get
                {
                    return _thresholdInfo;
                }
            }

            /// <summary>
            /// The Filter item.
            /// </summary>
            [RepositoryItem("fcc04890-5368-4344-8624-9db905c9d091")]
            public virtual Ranorex.Container Filter
            {
                get
                {
                    return _filterInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Filter item info.
            /// </summary>
            [RepositoryItemInfo("fcc04890-5368-4344-8624-9db905c9d091")]
            public virtual RepoItemInfo FilterInfo
            {
                get
                {
                    return _filterInfo;
                }
            }

            /// <summary>
            /// The NoneText item.
            /// </summary>
            [RepositoryItem("ed2e6d66-1e77-45ad-bb32-d90d07a73a83")]
            public virtual Ranorex.Text NoneText
            {
                get
                {
                    return _nonetextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NoneText item info.
            /// </summary>
            [RepositoryItemInfo("ed2e6d66-1e77-45ad-bb32-d90d07a73a83")]
            public virtual RepoItemInfo NoneTextInfo
            {
                get
                {
                    return _nonetextInfo;
                }
            }

            /// <summary>
            /// The MaxText item.
            /// </summary>
            [RepositoryItem("024dea1c-6184-4359-9836-f51dcdd8f495")]
            public virtual Ranorex.Text MaxText
            {
                get
                {
                    return _maxtextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The MaxText item info.
            /// </summary>
            [RepositoryItemInfo("024dea1c-6184-4359-9836-f51dcdd8f495")]
            public virtual RepoItemInfo MaxTextInfo
            {
                get
                {
                    return _maxtextInfo;
                }
            }

            /// <summary>
            /// The Fill item.
            /// </summary>
            [RepositoryItem("4b81c6c1-619d-4bfb-b623-1a3bd83b3cee")]
            public virtual Ranorex.CheckBox Fill
            {
                get
                {
                    return _fillInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The Fill item info.
            /// </summary>
            [RepositoryItemInfo("4b81c6c1-619d-4bfb-b623-1a3bd83b3cee")]
            public virtual RepoItemInfo FillInfo
            {
                get
                {
                    return _fillInfo;
                }
            }

            /// <summary>
            /// The TouchBoundary item.
            /// </summary>
            [RepositoryItem("5fa6715f-d154-46a1-ace7-467c984e2bc3")]
            public virtual Ranorex.CheckBox TouchBoundary
            {
                get
                {
                    return _touchboundaryInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The TouchBoundary item info.
            /// </summary>
            [RepositoryItemInfo("5fa6715f-d154-46a1-ace7-467c984e2bc3")]
            public virtual RepoItemInfo TouchBoundaryInfo
            {
                get
                {
                    return _touchboundaryInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}